#1) Arithmetic 2019.0904 MrG
show('#1) Arithmetic 2019.0904 MrG')
show('3+8=',3+8)
show('3-8=',3-8)
show('3*8=',3*8)
show('3/8=',(3/8).n())
show('3^8=',3^8)
show('')
#2) Algebra
show('#2) Algebra')
f(x)=x+2;show('f(x)=',f(x))
g(x)=2*x-3;show('g(x)=',g(x))
show('f(x)+g(x)=',f(x)+g(x))
show('f(x)-g(x)=',f(x)-g(x))
show('f(x)*g(x)=',expand(f(x)*g(x)))
show('(2*x^2+x-6)/(x+2)=',((2*x^2+x-6)/(x+2)).simplify_rational())
show('Binomial Expansion:')
for n in range(5):
    show(expand((x+1)^n))
show('')
#3) Solving Equations
show('#3) Solving Equations')
f(x)=x^2+2*x-1;show('f(x)=',f(x))
g(x)=x^2+2*x;show('f(x)=',g(x))
h(x)=x^2+2*x+1;show('f(x)=',h(x))
p(x)=x^2+2*x+2;show('f(x)=',p(x))
show('f(x)==0:',solve(f(x)==0,x))
show('g(x)==0:',solve(g(x)==0,x))
show('h(x)==0:',solve(h(x)==0,x))
show('p(x)==0:',solve(p(x)==0,x))
plot([f(x),g(x),h(x),p(x)],-3,3)
show('')
show('Find the Discriminant!')
def disc(a,b,c):
    return b^2-4*a*c
show('disc(1,2,-1)=',disc(1,2,-1))
show('disc(1,2,0)=',disc(1,2,0))
show('disc(1,2,1)=',disc(1,2,1))
show('disc(1,2,2)=',disc(1,2,2))
show('')
show('Use the Quadratic Formula!')
def quad(a,b,c):
    real=-b/(2*a)
    imag=sqrt(disc(a,b,c))/(2*a)
    return [real+imag, real-imag]
show('quad(1,2,-1)=',quad(1,2,-1))
show('quad(1,2,0)=',quad(1,2,0))
show('quad(1,2,1)=',quad(1,2,1))
show('quad(1,2,2)=',quad(1,2,2))
show('')
show('Plot The Functions!')
plot([f(x),g(x),h(x),p(x)],-3,3)
