#CSH102 2019.0911 MrG
show('#1) Given {a,b}')
show('#1) Find subsets: {}, {a}, {b}, {a,b}')
show('')
show('#2) Given {1,2,3}')
show('#2) Find subsets: {}, {1}, {2}, {3}, {1,2}, {1,3}, {2,3}, {1,2,3}')
show('#2) Conclusion If a set has cardinality n, Then number of subsets = 2^n')
show('')
show('#3) Is {2,4,3,5,9}-->{a,b,c,d,e} a Function? Yes!')
show('#3) 2-->e')
show('#3) 4-->a')
show('#3) 3-->d')
show('#3) 5-->c')
show('#3) 9-->b')
show('')
show('#4) Is {2,7,25}-->{a,b} a Function? Yes!')
show('#4) 2-->b')
show('#4) 7-->a')
show('#4) 25-->b')
show('')
show('#5) Is {2,7,25}-->{a,b,c,d} a Function? No!')
show('#5) 2-->c')
show('#5) 7-->a')
show('#5) 25-->d')
show('#5) 7-->b')
show('')
show('#6) Map the set of all Integers to 3 outcomes')
show('#6) {...,-3,-2,-1,0,+1,+2,+3,...} -->{-1,0,+1}')
show('#6) x<0 --> -1')
show('#6) x==0 --> 0')
show('#6) x>0 --> +1')
show('')
show('#7) If the cardinality of the domain is 17')
show('#7) Then the cardinality of the range is at most 17 and a least 1')
show('')
show('#8) Domain={1,2,3}, Range={a,b,c}, how many posible combinations of output?')
show('#8) (a,a,a),(a,a,b),(a,a,c),')
show('#8) (b,b,b),(b,b,a),(b,b,c),')
show('#8) (c,c,c),(c,c,a),(c,c,b),')
show('#8) (a,b,a),(a,b,b),(a,b,c),...')
show('#8) Counting Principle: 3*3*3 = 27')
show('')
show('#9) Map set of all Inegers to the set of Odd Integers')
show('#9) f(n)=2*n-1, n is an Integer')
def odd(n):
    return 2*n-1
show('odd(-3)=',odd(-3))
show('')
show('#10) f(word) = 1st letter in word')
def firstLetter(word):
    return word[0]
show('firstLetter("Baldwin")=',firstLetter("Baldwin"))
show('')
show('#11) map [-1,1] --> [0,1]')
show(plot(sqrt(1-x^2),aspect_ratio=1))
def circle(x):
    return sqrt(1-x^2)
show('circle(-1)=',circle(-1))
show('circle(-0.5)=',circle(-0.5))
show('circle(0)=',circle(0))
show('circle(0.5)=',circle(0.5))
show('circle(0.25)=',circle(0.25))
show('circle(1)=',circle(1))
show('')
show('#12) map (0,1] --> [1,inf)')
def flip(x):
    return 1/x
show('flip(1)=',flip(1))
show('flip(0.75)=',flip(0.75))
show('flip(3/4)=',flip(3/4))
show('flip(0.6)=',flip(0.6))
show('flip(3/5)=',flip(3/5))
show('flip(0.0001)=',flip(0.0001))
show('flip(1/10000)=',flip(1/10000))