#CSH103 Defining Functions 2019.0916 MrG
show('#1) Domain x!=2, Range y!=0')
f(x)=1/(x-2);show('f(x)=',f(x))
show(plot(f(x),xmin=-30,xmax=30,ymin=-10,ymax=10))
show('')
show('#2) Domain x>=-1, Range y>=0')
g(x)=sqrt(1+x);show('g(x)=',g(x))
show(plot(g(x),-1,10))
show('')
show('#3) Domain -1<=x<=1, Range 0<=y<=1')
h(x)=sqrt(1-x^2);show('h(x)=',h(x))
plot(h(x),aspect_ratio=1)
show('')
show('#4) Domain = {100,...,999} only integers')
show('#4) Range = {1,...,27} only integers')
show('#4) Cardinality(Domain)=900')
show('#4) Cardinality(Range)=27')
show('')
show('#5) {1,2,3,...} --> {2,5,10...}')
def h(n):
    return n^2+1
show('h(1)=',h(1))
show('h(2)=',h(2))
show('h(6)=',h(6))
show('')
show('#8) Define a function (-1,1) --> (-inf,+inf)')
f(x)=x/sqrt(1-x^2);show('f(x)=',f(x))
plot(f(x))
show('')
show('#9) Compositions')
f(x)=-2*x+1;show('f(x)=',f(x))
g(x)=x-1;show('g(x)=',g(x))
show('f(g(1))=',f(g(1)))
show('g(f(1))=',g(f(1)))
show('')
show('#10) Prove that the 1st n positive consecutive odd integers sum to n^2')
show('1=',1)
show('1+3=',4)
show('1+3+5=',9)
show('1+3+5+...+2*n=n^2')
show('range(1,10,2)=',range(1,10,2))
show('sum(range(1,10,2))=',sum(range(1,10,2)))
def sumOdd(n):
    show(range(1,2*n,2))
    return (sum(range(1,2*n,2)))
show('sumOdd(9)=',sumOdd(9))
