#CSH403 What Is A Series 2019.1216 MrG 
show('#1&2) show that an arithmetic series = n*(a(1)+a(n))/2')
var('a,d')
a(n)=a+d*n;show('a(n)=',a(n))
for n in range(1,6):
    show(a(n))
show('5*(a(1)+a(5))/2=',5*(a(1)+a(5))/2)
show('')

show('#3) sigma(1/(n*(n+1)),n,1,N))=1-1/(N+1)')
b(n)=1/(n*(n+1));show('b(n)=',b(n))
N=range(1,10);show('N=',N)
show('b(n)=',[b(n) for n in N])
show('sum=',sum([b(n) for n in N]))
show('')

show('#4&5) sigma(1/2^n),n,1,N))=1-1/2^N')
b(n)=1/2^n;show('b(n)=',b(n))
N=range(1,10);show('N=',N)
show('b(n)=',[b(n) for n in N])
show('sum=',sum([b(n) for n in N]))
show(plot([1-1/2^x,1/2+1/4+1/8],0,3))
show('')

show('#6) evaluate sigma(d*10*d,d,1,6)')
c(d)=d*10^d
D=range(1,7);show('D=',D)
show('c(d)=',[c(d) for d in D])
show('sum=',sum([c(d) for d in D]))
show('')

show('#7) sigma(2^k-k,k,1,n)=sigma(2^k,k,1,n)-sigma(k,k,1,n)')
a(k)=2^k;show('a(k)=',a(k))
b(k)=k;show('b(k)=',b(k))
c(k)=a(k)-b(k);show('c(k)=',c(k))
K=range(1,5);show('K=',K)
show('a(k)=',[a(k) for k in K])
show('b(k)=',[b(k) for k in K])
show('c(k)=',[c(k) for k in K])
show('sigma(a(k),k,1,4)=',sum([a(k) for k in K]))
show('sigma(b(k),k,1,4)=',sum([b(k) for k in K]))
show('sigma(c(k),k,1,4)=',sum([c(k) for k in K]))
show('')

show('#8a) prove: 1+2+3+...+n=n(n+1)/2')
show('#8a) prove: 1+2+3+...+n=a*n^2+b*n+c')
show('#8a) n=0: 0==c')
show('#8a) n=1: 1=a+b+c')
show('#8a) n=2: 3=4*a+2*b+c')
var('a,b,c,y,z')
show(solve([0==c,1==a+b+c,3==4*a+2*b+c],(a,b,c)))
show(solve(1==x+y,y))
show(solve(3==4*x+2*y,y))
plot([1-x,(3-4*x)/2])
show('')

show('#8b) prove: 1^2+2^2+3^2+...+n^2=a*n^3+b*n^2+c*n+d')
show('#8b) n=0: 0==d')
show('#8b) n=1: 1=a+b+c+d')
show('#8b) n=2: 5=8*a+4*b+2*c+d')
show('#8b) n=3: 14=27*a+9*b+3*c+d')
show(solve([1==a+b+c,5==8*a+4*b+2*c,14==27*a+9*b+3*c],(a,b,c)))
show(solve(1==x+y+z,z))
show(solve(5==8*x+4*y+2*z,z))
show(solve(14==27*x+9*y+3*z,z))
p1=plot3d(-x-y+1,(x,0,1),(y,0,1),color='red')
p2=plot3d(-4*x-2*y+5/2,(x,0,1),(y,0,1))
p3=plot3d(-9*x-3*y+14/3,(x,0,1),(y,0,1),color='green')
show(p1+p2+p3)